data:
  raw_path: "data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  processed_path: "data/processed/processed_data.csv"
  test_size: 0.2
  random_state: 42

features:
  target: "Churn"
  categorical_features:
    - "gender"
    - "Partner"
    - "Dependents"
    - "PhoneService"
    - "MultipleLines"
    - "InternetService"
    - "OnlineSecurity"
    - "OnlineBackup"
    - "DeviceProtection"
    - "TechSupport"
    - "StreamingTV"
    - "StreamingMovies"
    - "Contract"
    - "PaperlessBilling"
    - "PaymentMethod"
  numerical_features:
    - "SeniorCitizen"
    - "tenure"
    - "MonthlyCharges"
    - "TotalCharges"

models:
  save_path: "models/"